name: fix_my_diet
description: AI-powered dietician & Ayurvedic consultant for Indian users.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.8.0
  google_sign_in: ^6.2.2
  google_generative_ai: ^0.4.9
  shared_preferences: ^2.5.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
