class PricingDatabase {
  static const Map<String, PriceEntry> items = {
    'rice': PriceEntry('Rice (Regular)', 55, 'kg'),
    'basmati rice': PriceEntry('Basmati Rice', 95, 'kg'),
    'brown rice': PriceEntry('Brown Rice', 110, 'kg'),
    'wheat flour': PriceEntry('Wheat Flour (Atta)', 35, 'kg'),
    'atta': PriceEntry('Wheat Flour (Atta)', 35, 'kg'),
    'maida': PriceEntry('Maida', 40, 'kg'),
    'besan': PriceEntry('Besan (Gram Flour)', 85, 'kg'),
    'suji': PriceEntry('Suji / Rava', 45, 'kg'),
    'rava': PriceEntry('Suji / Rava', 45, 'kg'),
    'poha': PriceEntry('Poha (Flattened Rice)', 50, 'kg'),
    'oats': PriceEntry('Oats', 120, 'kg'),
    'daliya': PriceEntry('Daliya (Broken Wheat)', 45, 'kg'),
    'ragi': PriceEntry('Ragi (Finger Millet)', 60, 'kg'),
    'jowar': PriceEntry('Jowar (Sorghum)', 55, 'kg'),
    'bajra': PriceEntry('Bajra (Pearl Millet)', 45, 'kg'),
    'toor dal': PriceEntry('Toor Dal', 160, 'kg'),
    'moong dal': PriceEntry('Moong Dal', 130, 'kg'),
    'chana dal': PriceEntry('Chana Dal', 90, 'kg'),
    'urad dal': PriceEntry('Urad Dal', 120, 'kg'),
    'masoor dal': PriceEntry('Masoor Dal', 100, 'kg'),
    'rajma': PriceEntry('Rajma (Kidney Beans)', 140, 'kg'),
    'chole': PriceEntry('Chole (Chickpeas)', 90, 'kg'),
    'kabuli chana': PriceEntry('Kabuli Chana', 130, 'kg'),
    'lobia': PriceEntry('Lobia (Black-eyed Peas)', 110, 'kg'),
    'soybean': PriceEntry('Soybean', 80, 'kg'),
    'sprouts': PriceEntry('Sprouts', 80, 'kg'),
    'milk': PriceEntry('Milk', 66, 'litre'),
    'curd': PriceEntry('Curd / Dahi', 70, 'kg'),
    'dahi': PriceEntry('Curd / Dahi', 70, 'kg'),
    'paneer': PriceEntry('Paneer', 360, 'kg'),
    'butter': PriceEntry('Butter', 520, 'kg'),
    'ghee': PriceEntry('Ghee (Desi)', 600, 'litre'),
    'cheese': PriceEntry('Cheese', 420, 'kg'),
    'buttermilk': PriceEntry('Buttermilk / Chaas', 30, 'litre'),
    'chaas': PriceEntry('Buttermilk / Chaas', 30, 'litre'),
    'cream': PriceEntry('Cream', 300, 'litre'),
    'egg': PriceEntry('Egg', 7, 'piece'),
    'eggs': PriceEntry('Eggs', 84, 'dozen'),
    'chicken': PriceEntry('Chicken', 220, 'kg'),
    'fish': PriceEntry('Fish (Rohu)', 250, 'kg'),
    'mutton': PriceEntry('Mutton', 700, 'kg'),
    'prawns': PriceEntry('Prawns', 450, 'kg'),
    'potato': PriceEntry('Potato (Aloo)', 30, 'kg'),
    'onion': PriceEntry('Onion', 40, 'kg'),
    'tomato': PriceEntry('Tomato', 40, 'kg'),
    'spinach': PriceEntry('Spinach (Palak)', 30, 'bunch'),
    'palak': PriceEntry('Spinach (Palak)', 30, 'bunch'),
    'methi': PriceEntry('Methi (Fenugreek)', 30, 'bunch'),
    'cabbage': PriceEntry('Cabbage', 30, 'kg'),
    'cauliflower': PriceEntry('Cauliflower', 40, 'kg'),
    'capsicum': PriceEntry('Capsicum', 60, 'kg'),
    'carrot': PriceEntry('Carrot (Gajar)', 40, 'kg'),
    'beetroot': PriceEntry('Beetroot', 40, 'kg'),
    'cucumber': PriceEntry('Cucumber (Kheera)', 30, 'kg'),
    'bottle gourd': PriceEntry('Bottle Gourd (Lauki)', 30, 'kg'),
    'lauki': PriceEntry('Bottle Gourd (Lauki)', 30, 'kg'),
    'bitter gourd': PriceEntry('Bitter Gourd (Karela)', 50, 'kg'),
    'karela': PriceEntry('Bitter Gourd (Karela)', 50, 'kg'),
    'lady finger': PriceEntry('Lady Finger (Bhindi)', 50, 'kg'),
    'bhindi': PriceEntry('Lady Finger (Bhindi)', 50, 'kg'),
    'brinjal': PriceEntry('Brinjal (Baingan)', 40, 'kg'),
    'peas': PriceEntry('Green Peas', 80, 'kg'),
    'mushroom': PriceEntry('Mushroom', 150, 'kg'),
    'sweet potato': PriceEntry('Sweet Potato', 40, 'kg'),
    'radish': PriceEntry('Radish (Mooli)', 25, 'kg'),
    'green chili': PriceEntry('Green Chili', 80, 'kg'),
    'ginger': PriceEntry('Ginger (Adrak)', 120, 'kg'),
    'garlic': PriceEntry('Garlic (Lehsun)', 150, 'kg'),
    'coriander': PriceEntry('Coriander (Dhaniya)', 20, 'bunch'),
    'curry leaves': PriceEntry('Curry Leaves', 10, 'bunch'),
    'mint': PriceEntry('Mint (Pudina)', 15, 'bunch'),
    'lemon': PriceEntry('Lemon (Nimbu)', 5, 'piece'),
    'banana': PriceEntry('Banana', 50, 'dozen'),
    'apple': PriceEntry('Apple', 150, 'kg'),
    'pomegranate': PriceEntry('Pomegranate (Anar)', 140, 'kg'),
    'papaya': PriceEntry('Papaya', 40, 'kg'),
    'guava': PriceEntry('Guava (Amrud)', 60, 'kg'),
    'orange': PriceEntry('Orange (Santra)', 70, 'kg'),
    'watermelon': PriceEntry('Watermelon', 20, 'kg'),
    'mango': PriceEntry('Mango', 100, 'kg'),
    'dates': PriceEntry('Dates (Khajur)', 250, 'kg'),
    'dry fruits': PriceEntry('Mixed Dry Fruits', 800, 'kg'),
    'almonds': PriceEntry('Almonds (Badam)', 900, 'kg'),
    'cashews': PriceEntry('Cashews (Kaju)', 950, 'kg'),
    'walnuts': PriceEntry('Walnuts (Akhrot)', 1000, 'kg'),
    'peanuts': PriceEntry('Peanuts (Mungfali)', 120, 'kg'),
    'flax seeds': PriceEntry('Flax Seeds (Alsi)', 200, 'kg'),
    'sesame': PriceEntry('Sesame (Til)', 180, 'kg'),
    'coconut': PriceEntry('Coconut (Nariyal)', 25, 'piece'),
    'coconut oil': PriceEntry('Coconut Oil', 200, 'litre'),
    'mustard oil': PriceEntry('Mustard Oil', 180, 'litre'),
    'sunflower oil': PriceEntry('Sunflower Oil', 150, 'litre'),
    'olive oil': PriceEntry('Olive Oil', 500, 'litre'),
    'sugar': PriceEntry('Sugar', 42, 'kg'),
    'jaggery': PriceEntry('Jaggery (Gur)', 80, 'kg'),
    'honey': PriceEntry('Honey', 350, 'kg'),
    'salt': PriceEntry('Salt', 20, 'kg'),
    'turmeric': PriceEntry('Turmeric (Haldi)', 200, 'kg'),
    'red chili powder': PriceEntry('Red Chili Powder', 300, 'kg'),
    'coriander powder': PriceEntry('Coriander Powder', 200, 'kg'),
    'cumin': PriceEntry('Cumin (Jeera)', 350, 'kg'),
    'mustard seeds': PriceEntry('Mustard Seeds (Rai)', 120, 'kg'),
    'tea': PriceEntry('Tea Leaves', 350, 'kg'),
    'coffee': PriceEntry('Coffee Powder', 500, 'kg'),
    'bread': PriceEntry('Bread', 40, 'pack'),
    'biscuit': PriceEntry('Biscuit', 30, 'pack'),
    'noodles': PriceEntry('Noodles', 15, 'pack'),
    'vermicelli': PriceEntry('Vermicelli (Sevai)', 55, 'kg'),
    'giloy': PriceEntry('Giloy Powder', 200, '100g'),
    'giloy powder': PriceEntry('Giloy Powder', 200, '100g'),
    'ashwagandha': PriceEntry('Ashwagandha Powder', 250, '100g'),
    'ashwagandha powder': PriceEntry('Ashwagandha Powder', 250, '100g'),
    'triphala': PriceEntry('Triphala Powder', 180, '100g'),
    'triphala powder': PriceEntry('Triphala Powder', 180, '100g'),
    'shikakai': PriceEntry('Shikakai Powder', 120, '100g'),
    'shikakai powder': PriceEntry('Shikakai Powder', 120, '100g'),
    'amla': PriceEntry('Amla Powder', 150, '100g'),
    'amla powder': PriceEntry('Amla Powder', 150, '100g'),
    'tulsi': PriceEntry('Tulsi Drops', 130, 'bottle'),
    'neem': PriceEntry('Neem Powder', 120, '100g'),
    'multani mitti': PriceEntry('Multani Mitti', 60, '200g'),
    'rose water': PriceEntry('Rose Water (Gulab Jal)', 80, 'bottle'),
    'aloe vera': PriceEntry('Aloe Vera Gel', 120, '200ml'),
    'castor oil': PriceEntry('Castor Oil', 150, '200ml'),
    'bhringraj': PriceEntry('Bhringraj Oil', 180, '200ml'),
    'methi seeds': PriceEntry('Methi Seeds (Fenugreek)', 100, 'kg'),
    'ajwain': PriceEntry('Ajwain (Carom Seeds)', 200, 'kg'),
    'saunf': PriceEntry('Saunf (Fennel Seeds)', 180, 'kg'),
    'black pepper': PriceEntry('Black Pepper (Kali Mirch)', 600, 'kg'),
    'cloves': PriceEntry('Cloves (Laung)', 1200, 'kg'),
    'cardamom': PriceEntry('Cardamom (Elaichi)', 2000, 'kg'),
    'cinnamon': PriceEntry('Cinnamon (Dalchini)', 400, 'kg'),
    'nutritional yeast': PriceEntry('Nutritional Yeast', 500, '200g'),
    'isabgol': PriceEntry('Isabgol (Psyllium Husk)', 180, '200g'),
  };

  static PriceEntry? lookup(String name) {
    final key = name.toLowerCase().trim();
    if (items.containsKey(key)) return items[key];
    for (final entry in items.entries) {
      if (key.contains(entry.key) || entry.key.contains(key)) {
        return entry.value;
      }
    }
    return null;
  }
}

class PriceEntry {
  final String displayName;
  final int priceInr;
  final String unit;
  const PriceEntry(this.displayName, this.priceInr, this.unit);

  String get formatted => '₹$priceInr/$unit';
}
